<Project Sdk="Microsoft.NET.Sdk">
  <!-- Infrastructure: detalhes técnicos (banco de dados, EF Core, MySQL). -->
  <ItemGroup>
    <ProjectReference Include="..\MioDolce.Application\MioDolce.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="MySql.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
  </ItemGroup>
</Project>
